"""BIP340 Schnorr math for a DLC oracle - the Python counterpart to
lnurl-wallet's own `src/addons/dlc/dlc.ts`, which this must match
byte-for-byte (cross-checked in tests/test_oracle.py against real vectors
generated by that TypeScript implementation - not just internally
self-consistent).

The core idea: an oracle commits ahead of time to a nonce point R
(alongside its long-term pubkey P). For a specific outcome message m,
define

  e = tagged_hash("BIP0340/challenge", R || P || m)
  T = R + e*P                                    <- the "outcome point"

A real BIP340 signature (R, s) for m satisfies s*G = T - i.e. s IS the
discrete log of T. This is what a note's taproot leaf locks to (as a plain
`<T> OP_CHECKSIG`, see the sibling `betlocker` addon in lnurl-wallet) -
nobody can compute s before the oracle actually signs m.

Deliberately NOT `PrivateKey.sign_schnorr` (coincurve's own BIP340 signer):
that derives its own fresh nonce internally per BIP340's default signing
algorithm. The entire DLC mechanism depends on reusing the pre-announced
nonce, so attest() implements BIP340's signing algorithm by hand with an
externally supplied nonce secret in place of that internal derivation -
same even-y parity correction (for both the signing key and the nonce)
BIP340 itself requires, same reasoning lnurl-mint's own ct1.py uses
`PublicKey(b"\\x02" + x)` to lift an x-only key back to a point.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from coincurve import PublicKey

# secp256k1's own group order - a universal constant, not something to
# derive at runtime
CURVE_ORDER = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

# dlc.ts's own tag for the message an attestation actually signs - NOT the
# raw outcome string. See that file's own comment on where this is sourced
# from and its one open verification gap (not yet cross-checked against a
# real external oracle's own vectors).
ATTESTATION_TAG = "DLC/oracle/attestation/v0"


def _tagged_hash(tag: str, *chunks: bytes) -> bytes:
    tag_hash = hashlib.sha256(tag.encode()).digest()
    return hashlib.sha256(tag_hash + tag_hash + b"".join(chunks)).digest()


def _outcome_message_hash(outcome: str) -> bytes:
    return _tagged_hash(ATTESTATION_TAG, outcome.encode("utf-8"))


def _parse_hex32(value: str, label: str) -> bytes:
    trimmed = value.strip().lower()
    if len(trimmed) != 64 or any(c not in "0123456789abcdef" for c in trimmed):
        raise ValueError(f"{label} must be 32 bytes of hex.")
    return bytes.fromhex(trimmed)


def _lift_x_even(x: bytes) -> PublicKey:
    """The point at x-coordinate `x` with even y (BIP340's own lift_x -
    every x-only key in this scheme names exactly this point)."""
    return PublicKey(b"\x02" + x)


def _is_even_y(point: PublicKey) -> bool:
    _, y = point.point()
    return y % 2 == 0


def outcome_point(oracle_pubkey_hex: str, nonce_hex: str, outcome: str) -> str:
    """T = R + e*P - the pubkey a specific outcome's leaf locks to,
    computable by anyone the instant the oracle PUBLISHES its announcement
    (P, R), long before the event resolves. Raises ValueError on
    malformed hex."""
    p_bytes = _parse_hex32(oracle_pubkey_hex, "Oracle pubkey")
    r_bytes = _parse_hex32(nonce_hex, "Nonce")
    e = (
        int.from_bytes(
            _tagged_hash(
                "BIP0340/challenge", r_bytes, p_bytes, _outcome_message_hash(outcome)
            ),
            "big",
        )
        % CURVE_ORDER
    )
    r_point = _lift_x_even(r_bytes)
    p_point = _lift_x_even(p_bytes)
    e_p = p_point.multiply(e.to_bytes(32, "big"))
    t_point = PublicKey.combine_keys([r_point, e_p])
    return t_point.format(compressed=True)[1:].hex()


@dataclass(frozen=True)
class Attestation:
    outcome: str
    signature_hex: str  # 64-byte hex: R (32) || s (32)


def attest(oracle_secret_hex: str, nonce_secret_hex: str, outcome: str) -> Attestation:
    """The oracle's own act: sign whichever outcome actually happened,
    with the SAME nonce secret whose public point it already announced as
    R. Raises ValueError on malformed hex."""
    raw_d = int.from_bytes(_parse_hex32(oracle_secret_hex, "Oracle secret key"), "big")
    raw_k = int.from_bytes(_parse_hex32(nonce_secret_hex, "Nonce secret"), "big")
    if not (0 < raw_d < CURVE_ORDER) or not (0 < raw_k < CURVE_ORDER):
        raise ValueError("Secret key and nonce secret must each be a valid scalar.")

    d_point = PublicKey.from_secret(raw_d.to_bytes(32, "big"))
    d = raw_d if _is_even_y(d_point) else (CURVE_ORDER - raw_d) % CURVE_ORDER
    p_bytes = d_point.format(compressed=True)[1:]  # x-only: parity-independent

    k_point = PublicKey.from_secret(raw_k.to_bytes(32, "big"))
    k = raw_k if _is_even_y(k_point) else (CURVE_ORDER - raw_k) % CURVE_ORDER
    r_bytes = k_point.format(compressed=True)[1:]

    e = (
        int.from_bytes(
            _tagged_hash(
                "BIP0340/challenge", r_bytes, p_bytes, _outcome_message_hash(outcome)
            ),
            "big",
        )
        % CURVE_ORDER
    )
    s = (k + e * d) % CURVE_ORDER

    return Attestation(
        outcome=outcome, signature_hex=(r_bytes + s.to_bytes(32, "big")).hex()
    )


def verify_attestation(
    oracle_pubkey_hex: str, nonce_hex: str, attestation: Attestation
) -> bool:
    """A real attestation is more than "a valid BIP340 signature over this
    outcome" - it must also use the SAME nonce the oracle already
    announced (R), or it isn't a signature over the pre-committed event at
    all. Checks both. Never raises."""
    try:
        sig = bytes.fromhex(attestation.signature_hex.strip().lower())
        if len(sig) != 64:
            return False
        sig_r, sig_s = sig[:32], sig[32:]
        if sig_r.hex() != nonce_hex.strip().lower():
            return False
        s = int.from_bytes(sig_s, "big")
        if not (0 < s < CURVE_ORDER):
            return False
        p_bytes = _parse_hex32(oracle_pubkey_hex, "Oracle pubkey")
        e = (
            int.from_bytes(
                _tagged_hash(
                    "BIP0340/challenge",
                    sig_r,
                    p_bytes,
                    _outcome_message_hash(attestation.outcome),
                ),
                "big",
            )
            % CURVE_ORDER
        )
        s_g = PublicKey.from_secret(s.to_bytes(32, "big"))
        p_point = _lift_x_even(p_bytes)
        e_p = p_point.multiply(e.to_bytes(32, "big"))
        r_point = _lift_x_even(sig_r)
        expected = PublicKey.combine_keys([r_point, e_p])
        return s_g.format(compressed=True) == expected.format(compressed=True)
    except Exception:
        return False


def pubkey_from_secret(secret_hex: str) -> str:
    secret = _parse_hex32(secret_hex, "Secret key")
    return PublicKey.from_secret(secret).format(compressed=True)[1:].hex()


def generate_keypair() -> tuple[str, str]:
    """(secret_key_hex, pubkey_hex) - used for both an oracle's long-term
    identity and a per-event nonce, which are the exact same math (a
    random scalar and its x-only point). Cryptographically secure
    randomness via ``os.urandom`` (coincurve's own PrivateKey generation
    path)."""
    from coincurve import PrivateKey

    secret_bytes = PrivateKey().secret
    return secret_bytes.hex(), pubkey_from_secret(secret_bytes.hex())
