"""Cross-checked against lnurl-wallet's own src/addons/dlc/dlc.ts - the
TypeScript reference implementation this must match byte-for-byte for the
two services to actually interoperate. The vectors below were generated
by that TypeScript module (schnorr.getPublicKey/outcomePoint/attest), not
guessed - see this repo's DESIGN.md for how to regenerate them if
dlc.ts's own algorithm ever changes."""

import pytest

from app.crypto.oracle import (
    Attestation,
    attest,
    generate_keypair,
    outcome_point,
    pubkey_from_secret,
    verify_attestation,
)

# generated by dlc.ts: schnorr.getPublicKey(hexToBytes(sk)) for both keys,
# then outcomePoint(oraclePk, noncePk, "yes"/"no") and
# attest(oracleSk, nonceSk, "yes")
ORACLE_SK = "11" * 32
ORACLE_PK = "4f355bdcb7cc0af728ef3cceb9615d90684bb5b2ca5f859ab0f0b704075871aa"
NONCE_SK = "22" * 32
NONCE_PK = "466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27"
YES_POINT = "fd04e0fee1cf43a109db0e6b5d6e529d6f293c1bae9bde85a3bca88b4de1f83e"
NO_POINT = "696f871ce04e3ee5b7b6ddd35445690c6fed61a522d13d9435fd575289ca3837"
YES_ATTESTATION_SIG = (
    "466d7fcae563e5cb09a0d1870bb580344804617879a14949cf22285f1bae3f27"
    "010be76359f480c6cd296b4784456ca6ff14c70bf45fb896bf9fbd06c015122c"
)


def test_outcome_point_matches_the_typescript_reference():
    assert outcome_point(ORACLE_PK, NONCE_PK, "yes") == YES_POINT
    assert outcome_point(ORACLE_PK, NONCE_PK, "no") == NO_POINT


def test_attest_matches_the_typescript_reference_byte_for_byte():
    a = attest(ORACLE_SK, NONCE_SK, "yes")
    assert a.signature_hex == YES_ATTESTATION_SIG


def test_verify_attestation_accepts_the_typescript_generated_signature():
    ts_attestation = Attestation(outcome="yes", signature_hex=YES_ATTESTATION_SIG)
    assert verify_attestation(ORACLE_PK, NONCE_PK, ts_attestation) is True


def test_pubkey_from_secret_matches():
    assert pubkey_from_secret(ORACLE_SK) == ORACLE_PK
    assert pubkey_from_secret(NONCE_SK) == NONCE_PK


def test_precomputes_distinct_points_before_any_attestation_exists():
    _, pk1 = generate_keypair()
    _, pk2 = generate_keypair()
    yes = outcome_point(pk1, pk2, "yes")
    no = outcome_point(pk1, pk2, "no")
    assert yes != no
    assert len(bytes.fromhex(yes)) == 32


def test_attestation_reveals_a_real_key_for_exactly_that_outcome():
    from coincurve import PublicKey

    oracle_sk, oracle_pk = generate_keypair()
    nonce_sk, nonce_pk = generate_keypair()
    points = {
        "yes": outcome_point(oracle_pk, nonce_pk, "yes"),
        "no": outcome_point(oracle_pk, nonce_pk, "no"),
    }
    a = attest(oracle_sk, nonce_sk, "yes")
    assert verify_attestation(oracle_pk, nonce_pk, a) is True

    s_hex = a.signature_hex[64:]
    derived_pubkey = PublicKey.from_secret(bytes.fromhex(s_hex)).format(compressed=True)[
        1:
    ].hex()
    assert derived_pubkey == points["yes"]
    assert derived_pubkey != points["no"]


def test_rejects_a_signature_claiming_the_wrong_outcome_for_its_own_bytes():
    oracle_sk, oracle_pk = generate_keypair()
    nonce_sk, nonce_pk = generate_keypair()
    a = attest(oracle_sk, nonce_sk, "yes")
    forged = Attestation(outcome="no", signature_hex=a.signature_hex)
    assert verify_attestation(oracle_pk, nonce_pk, forged) is False


def test_rejects_an_attestation_signed_with_a_nonce_other_than_announced():
    oracle_sk, oracle_pk = generate_keypair()
    _, announced_nonce_pk = generate_keypair()
    actually_used_sk, _ = generate_keypair()
    a = attest(oracle_sk, actually_used_sk, "yes")
    # a plain BIP340 verify alone would pass this (it's genuinely valid) -
    # the nonce-matches-the-announcement check is what makes it fail
    assert verify_attestation(oracle_pk, announced_nonce_pk, a) is False


def test_rejects_a_signature_from_the_wrong_oracle():
    _, oracle_pk = generate_keypair()
    impostor_sk, _ = generate_keypair()
    nonce_sk, nonce_pk = generate_keypair()
    a = attest(impostor_sk, nonce_sk, "yes")
    assert verify_attestation(oracle_pk, nonce_pk, a) is False


def test_verify_never_raises_on_malformed_input():
    assert (
        verify_attestation("nope", "nope", Attestation(outcome="yes", signature_hex="nope"))
        is False
    )


def test_outcome_point_and_attest_raise_on_malformed_hex():
    with pytest.raises(ValueError):
        outcome_point("nope", "ab" * 32, "yes")
    with pytest.raises(ValueError):
        attest("nope", "ab" * 32, "yes")
